package com.fbse.recommentmobilesystem.common;

public class Msg {
//    public static final String QINGKONGQUEREN = "QINGKONGQUEREN";// 确定要清空顾客列表吗?
//    public static final String MEIYOUGUKE = "MEIYOUGUKE";// 没有顾客可以删除
//    public static final String DOUBLECLECKEXIT = "DOUBLECLECKEXIT";// 再按一次退出程序
//    public static final String DELSURE = "DELSURE";// 确定删除吗?
//    public static final String TISHI = "TISHI";// 提示
//    public static final String QUXIAO = "QUXIAO";// 取消
//    public static final String SERVRCEERROR = "SERVRCEERROR";// 服务器发生异常，请稍后再试
//    public static final String LIEBIAOSHIBAI = "LIEBIAOSHIBAI";// 数据加载失败
//    public static final String QUXML = "QUXML";// 正在加载数据...
//    public static final String SENDINFO = "SENDINFO";// 答案成功提交
//    public static final String ERRORSENDANSWER = "ERRORSENDANSWER";// 问卷调查提交失败
//    public static final String DEGNLUSHIBAI = "DEGNLUSHIBAI";// 登录失败
//    public static final String FUWUQIYICHANG = "FUWUQIYICHANG";// 服务器连接异常
//    public static final String NODATA = "NODATA";// 暂没有功能
//    public static final String EXITSURE = "EXITSURE";// 确定要注销吗?
//    
//    public static final String GINFO = "GINFO";// 已是第一页
//    public static final String TINFO = "TINFO";// 已是最后一页
//    public static final String CHANGESUCCESS = "CHANGESUCCESS";// 账户信息提交成功
//    public static final String SUBMITFAILED = "SUBMITFAILED";// 账户信息提交失败
//    public static final String NETERROR = "NETERROR";// 网络异常,请重新确认网络设置
//    public static final String PASSWORDSETFAILED = "PASSWORDSETFAILED";// 密码设置失败
//    public static final String SHOPERCI = "SHOPERCI";// 二期开发进行中,敬请期待
//    public static final String NEWVERSION = "NEWVERSION";// 版本更新
//    public static final String LOGINFAIL = "LOGINFAIL";// 账号或密码错误
//    public static final String ILLEGALLOGINNAME = "ILLEGALLOGINNAME";// 登录名为汉字、英文字符、数字和下划线，请勿输入特殊字符
//    public static final String PASSWORDINLLGEL = "PASSWORDINLLGEL";// 请重新确认密码
//    public static final String SUREPASSWORD = "SUREPASSWORD";// 两次输入密码不一致,请重新输入
//    public static final String SURE = "SURE";// 确定
//    public static final String PASSWORDCUOWU = "PASSWORDCUOWU";// 请重新确认密码
//    public static final String SUREYUANPASSWORD = "SUREYUANPASSWORD";// 原密码不正确
//    public static final String ILLEGALPASSWORD = "ILLEGALPASSWORD";// 密码设置为汉字、英文字符、数字、标点和下划线，请勿输入特殊字符
//    public static final String PASSWORDSETSUCCESS = "PASSWORDSETSUCCESS";// 设置成功
//    public static final String NOTNULL = "NOTNULL";// {0}不能为空
//    public static final String YICHAOCHANG = "YICHAOCHANG";// 您输入的字已超过{0}个文字长度
//    public static final String TIJIAOMA = "TIJIAOMA";// 确定提交问卷吗?
//    public static final String FANGQI = "FANGQI";// 确定放弃回答问卷吗?
//    public static final String QINGDAWAN = "QINGDAWAN";// 请回答完问卷
//    public static final String HAIMEIDA = "HAIMEIDA";// 您还没回答问卷
//    public static final String YIDAWAN = "YIDAWAN";// 已回答完该问卷
//    public static final String ZANWU = "ZANWU";// 暂无问卷调查
//    public static final String DAANING = "DAANING";// 正在提交问卷..
//
//    public static final String TJWX = "TJWX";// 确定要提交维修单吗？
//    public static final String SRYY = "SRYY";// 请输入维修原因
//    public static final String BXCG = "BXCG";// 报修成功
//    public static final String BXSB = "BXSB";// 报修失败
//    public static final String ZXSJ = "ZXSJ";// 已是最新数据
//    public static final String CXSJSB = "CXSJSB";// 查询数据失败
//    public static final String ZWBXSJ = "ZWBXSJ";// 暂无报修数据
//    public static final String JSSJSB = "JSSJSB";// 接收数据失败
//    public static final String GKLBQK = "GKLBQK";// 顾客列表将会清空，是否确定退出？
//    public static final String QDSCGK = "QDSCGK";// 确定删除该顾客吗？
//    public static final String QDSCXDGK = "QDSCXDGK";// 确定删除选定顾客吗？
//    public static final String REPEATUSERNAME = "REPEATUSERNAME";// 用户名已存在
//    public static final String SIMILARUSERNAME = "SIMILARUSERNAME";// 当前登录名与修改修改用户名一致
//
//    public static final String REGISTERSUCCESS = "REGISTERSUCCESS";// {0}登录成功
//    public static final String SUBMITING = "SUBMITING";// 正在提交注册信息，请耐心等待
//    public static final String SUREDELETEASSISTANT = "SUREDELETEASSISTANT";// 将该店员从列表中删除？
//    public static final String ONLOADINGDATA = "ONLOADINGDATA";// 正在加载数据...
//    public static final String NAMEISNULL = "NAMEISNULL";// 姓名为空，请确认输入
//    public static final String MOBILEISNULL = "MOBILEISNULL";// 电话为空，请确认输入
//    public static final String LOGINISNULL = "LOGINISNULL";// 登录名为空，请确认输入
//    public static final String LOGINNAMEOFPASSWORD = "LOGINNAMEOFPASSWORD";// 登录密码与确认密码不一致，请确认输入
//    public static final String INFOCHANGESUCCESS = "INFOCHANGESUCCESS";// 信息修改成功
//    public static final String INFOCHANGEFAILED = "INFOCHANGEFAILED";// 信息修改失败
//    public static final String INFOCHANGEEXCEPTION = "INFOCHANGEEXCEPTION";// 信息修改异常
//    public static final String TELANTSERVEREXCEPTION = "TELANTSERVEREXCEPTION";// 远程服务器异常
//    public static final String HOSTSERVEREXCEPTION = "HOSTSERVEREXCEPTION";// 本地服务器异常
//    public static final String MORETHANSUPER = "MORETHANSUPER";// 超出最大输入限制

    public static final String I001 = "I001";// 已是第一页
    public static final String I002 = "I002";// 已是最后一页
    public static final String I003 = "I003";// 再按一次退出程序
    public static final String I004 = "I004";// 提示
    public static final String I005 = "I005";// 取消
    public static final String I006 = "I006";// 正在加载数据...
    public static final String I007 = "I007";// 答案成功提交
//  public static final String I008 = "I008";// 暂没有功能
    public static final String I009 = "I009";// 账户信息提交成功
//  public static final String I010 = "I010";// 二期开发进行中,敬请期待
//  public static final String I011 = "I011";// 版本更新
    public static final String I012 = "I012";// 确定
    public static final String I013 = "I013";// 设置成功
    public static final String I014 = "I014";// 暂无问卷调查

    public static final String I015 = "I015"; // 正在提交问卷…
    public static final String I016 = "I016"; // 报修成功
    public static final String I017 = "I017"; // 已是最新数据
    public static final String I018 = "I018"; // 暂无报修数据
    public static final String I019 = "I019"; // {0}添加成功
    public static final String I020 = "I020"; // {0}修改成功
    public static final String I021 = "I021"; // {0}删除成功
    public static final String I022 = "I022"; // 暂无{0}数据
//  public static final String I023 = "I023"; // 修改{0}
//  public static final String I024 = "I024"; // 删除{0}
    public static final String I025 = "I025"; // 正在提交注册信息，请耐心等待
	public static final String I026 = "I026"; // 没有更多的数据
	public static final String I027 = "I027"; // 没有符合条件的数据
	
    public static final String Q001 = "Q001"; // 确定要清空顾客列表吗?
//  public static final String Q002 = "Q002"; // 确定删除吗?
    public static final String Q003 = "Q003"; // 确定要注销吗?
    public static final String Q004 = "Q004"; // 确定提交问卷吗?
    public static final String Q005 = "Q005"; // 确定放弃回答问卷吗?
    public static final String Q006 = "Q006"; // 确定要提交维修单吗？
    public static final String Q007 = "Q007"; // 顾客列表将会清空，是否确定退出？
//  public static final String Q008 = "Q008"; // 确定删除该顾客吗？
    public static final String Q009 = "Q009"; // 确定删除选定顾客吗？
	public static final String Q010 = "Q010"; // 确定添加{0}吗?
    public static final String Q011 = "Q011"; // 确定修改{0}吗?
//  public static final String Q012 = "Q012"; // 相同{0}的数据已经登录。
    public static final String Q013 = "Q013"; // 画面上有已编辑的项目，确定要返回到前画面吗？
//  public static final String Q014 = "Q014"; // 确定要返回到前画面吗？
    public static final String Q015 = "Q015"; // 确定删除{0}吗?
    public static final String W001 = "W001"; // 请回答完问卷
    public static final String W002 = "W002"; // 您还没回答问卷
    public static final String W003 = "W003"; // 已回答完该问卷
	public static final String W004 = "W004"; // 权限不够，不能修改
	public static final String W005 = "W005"; // 权限不够，不能删除
	
	
	
    public static final String E0001 = "E0001"; // 没有顾客可以删除
    public static final String E0002 = "E0002"; // 服务器发生异常，请稍后再试
    public static final String E0003 = "E0003"; // 数据加载失败
    public static final String E0004 = "E0004"; // 问卷调查提交失败
    public static final String E0005 = "E0005"; // {0}添加失败
    public static final String E0006 = "E0006"; // 服务器连接异常
    public static final String E0007 = "E0007"; // 账户信息提交失败
    public static final String E0008 = "E0008"; // 网络异常,请重新确认网络设置
    public static final String E0009 = "E0009"; // 密码设置失败
//  public static final String E0010 = "E0010"; // 账号或密码错误
    public static final String E0011 = "E0011"; // 登录名为汉字、英文字符、数字和下划线，请勿输入特殊字符
//  public static final String E0012 = "E0012"; // 请重新确认密码
    public static final String E0013 = "E0013"; // 两次输入密码不一致,请重新输入
    public static final String E0014 = "E0014"; // 原密码不正确
    public static final String E0015 = "E0015"; // 密码设置为汉字、英文字符、数字、标点和下划线，请勿输入特殊字符
    public static final String E0016 = "E0016"; // {0}不能为空
    public static final String E0017 = "E0017"; // 您输入的字已超过{0}个文字长度
    public static final String E0018 = "E0018"; // 请输入维修原因
    public static final String E0019 = "E0019"; // 报修失败
    public static final String E0020 = "E0020"; // 查询数据失败
    public static final String E0021 = "E0021"; // 接收数据失败
    public static final String E0022 = "E0022"; // 用户名已存在
//  public static final String E0023 = "E0023"; // 当前登录名与修改修改用户名一致
    public static final String E0024 = "E0024"; // {0}修改失败
    public static final String E0025 = "E0025"; // {0}删除失败
    public static final String E0026 = "E0026"; // 超出最大输入限制
    public static final String E0027 = "E0027"; // 本地服务器异常
    public static final String E0028 = "E0028"; // 远程服务器异常
    public static final String E0029 = "E0029"; // {0}只能输入半角数字
    public static final String E0030 = "E0030"; // {0}不能小于{1}
    public static final String E0031 = "E0031"; // {0}不能大于{1}
}
